version: 0.2

phases:
  install:
    commands:
      - echo "Building Hello world"
      - docker build -t helloworldddd .
  build:
    commands:
      - docker images
      - docker run helloworld echo "Hello, World!"
